import type { Product, Category } from "../types";

export const mockCategories: Category[] = [
  { id: "1", name: "Smartphones", slug: "smartphones" },
  { id: "2", name: "Tablets", slug: "tablets" },
  { id: "3", name: "Foldables", slug: "foldables" },
  { id: "4", name: "Budget Phones", slug: "budget-phones" },
];

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Iphone 17 Pro Max",
    description:
      "Ultra-slim smartphone with a matte finish and premium edge-to-edge metallic design.",
    price: 799.99,
    images: ["/images/photo1.webp"],
    category: "smartphones",
    brand: "Apple",
    rating: 4.5,
    reviewCount: 320,
    stock: 50,
    sellerId: "s1",
    createdAt: "2024-01-10",
  },
  {
    id: "2",
    name: "Apex Neon Glow",
    description:
      "Flagship phone featuring an immersive curved OLED display with dynamic neon ambient lighting indicators.",
    price: 999.99,
    originalPrice: 1099.99,
    images: ["/images/photo2.webp"],
    category: "smartphones",
    brand: "ApexMobile",
    rating: 4.8,
    reviewCount: 1240,
    stock: 35,
    sellerId: "s1",
    createdAt: "2024-01-15",
  },
  {
    id: "3",
    name: "Vibrant Duo Pack",
    description:
      "Sleek and colorful modern smartphones with multi-camera setups designed for the younger generation.",
    price: 450.0,
    images: ["/images/photo3.webp"],
    category: "smartphones",
    brand: "NovaTech",
    rating: 4.3,
    reviewCount: 512,
    stock: 80,
    sellerId: "s2",
    createdAt: "2024-02-12",
  },
  {
    id: "4",
    name: "Zenith Aesthetic Mono",
    description:
      "A minimalist smartphone setup focused on clean aesthetics, crisp display, and high-performance stock Android experience.",
    price: 599.99,
    images: ["/images/photo4.webp"],
    category: "smartphones",
    brand: "Zenith",
    rating: 4.6,
    reviewCount: 890,
    stock: 25,
    sellerId: "s3",
    createdAt: "2024-02-18",
  },
  {
    id: "5",
    name: "Cyber Desk Pro 5G",
    description:
      "High-end developer-centric phone optimized for deep multi-tasking, high frame rates, and heavy processing.",
    price: 999.99,
    originalPrice: 1299.99,
    images: ["/images/photo5.webp"],
    category: "smartphones",
    brand: "ApexMobile",
    rating: 4.9,
    reviewCount: 430,
    stock: 15,
    sellerId: "s1",
    createdAt: "2024-02-25",
  },
  {
    id: "6",
    name: "Lite Spark Handheld",
    description:
      "Ergonomic, lightweight phone built for comfortable one-handed use without compromising screen estate.",
    price: 299.99,
    images: ["/images/photo6.webp"],
    category: "smartphones",
    brand: "Horizon",
    rating: 4.2,
    reviewCount: 156,
    stock: 120,
    sellerId: "s2",
    createdAt: "2024-03-01",
  },
  {
    id: "7",
    name: "Nova Prism Pro",
    description:
      "Features a dazzling multi-colored back gradient with an advanced punch-hole display and AI quad-camera setup.",
    price: 649.99,
    images: ["/images/photo7.webp"],
    category: "smartphones",
    brand: "NovaTech",
    rating: 4.5,
    reviewCount: 765,
    stock: 90,
    sellerId: "s2",
    createdAt: "2024-03-05",
  },
  {
    id: "8",
    name: "Zenith Flat Slate",
    description:
      "A super-slim profile smartphone designed with sharp angles, seamless glass back, and premium pocket fit.",
    price: 749.99,
    originalPrice: 799.99,
    images: ["/images/photo8.webp"],
    category: "smartphones",
    brand: "Zenith",
    rating: 4.4,
    reviewCount: 310,
    stock: 40,
    sellerId: "s3",
    createdAt: "2024-03-10",
  },
  {
    id: "9",
    name: "Alpha Grid Max",
    description:
      "High refresh rate screen featuring a clean grid layout interface, ideal for content consumption and social media.",
    price: 499.99,
    images: ["/images/photo9.webp"],
    category: "smartphones",
    brand: "ApexMobile",
    rating: 4.3,
    reviewCount: 620,
    stock: 110,
    sellerId: "s1",
    createdAt: "2024-03-12",
  },
  {
    id: "10",
    name: "Horizon Crimson Glow",
    description:
      "A striking smartphone bathed in dramatic red ambient light, packing a powerful night-photography sensor.",
    price: 849.99,
    images: ["/images/photo10.webp"],
    category: "smartphones",
    brand: "Horizon",
    rating: 4.7,
    reviewCount: 289,
    stock: 30,
    sellerId: "s2",
    createdAt: "2024-03-15",
  },
  {
    id: "11",
    name: "Horizon Minimal Sleek",
    description:
      "Bright orange aesthetic variant featuring a dual-sensor camera array and ultra-fast charging capabilities.",
    price: 299.99,
    originalPrice: 349.99,
    images: ["/images/photo11.webp"],
    category: "smartphones",
    brand: "NovaTech",
    rating: 4.3,
    reviewCount: 415,
    stock: 75,
    sellerId: "s3",
    createdAt: "2024-03-18",
  },
  {
    id: "12",
    name: 'Zenith Pad Tab 10"',
    description:
      "High-resolution tablet perfect for digital art, office productivity, and streaming your favorite content.",
    price: 549.99,
    images: ["/images/photo16.webp"],
    category: "tablets",
    brand: "Zenith",
    rating: 4.6,
    reviewCount: 932,
    stock: 25,
    sellerId: "s3",
    createdAt: "2024-03-20",
  },
  {
    id: "13",
    name: "Alpha Tab Air",
    description:
      "Ultra-lightweight mobile tablet featuring a vivid display, minimal bezels, and snappy processing power.",
    price: 479.99,
    originalPrice: 529.99,
    images: ["/images/photo23.webp"],
    category: "tablets",
    brand: "ApexMobile",
    rating: 4.5,
    reviewCount: 510,
    stock: 60,
    sellerId: "s1",
    createdAt: "2024-03-22",
  },
  {
    id: "14",
    name: "Social Floating Grid",
    description:
      "A trendy phone optimized for creators, offering zero-latency floating UI interactions and advanced video stabilization.",
    price: 699.99,
    images: ["/images/photo13.webp"],
    category: "smartphones",
    brand: "NovaTech",
    rating: 4.6,
    reviewCount: 843,
    stock: 45,
    sellerId: "s2",
    createdAt: "2024-03-25",
  },
  {
    id: "15",
    name: "Levitating Gravity Pro",
    description:
      "Concept smartphone focusing on futuristic design, lightweight materials, and gesture-driven actions.",
    price: 999.99,
    images: ["/images/photo14.webp"],
    category: "smartphones",
    brand: "Zenith",
    rating: 4.8,
    reviewCount: 195,
    stock: 12,
    sellerId: "s3",
    createdAt: "2024-03-28",
  },
  {
    id: "16",
    name: "Apex Horizon Terra",
    description:
      "Rugged yet beautiful phone featuring earth-themed stock wallpapers and robust drop protection.",
    price: 580.0,
    images: ["/images/photo15.webp"],
    category: "smartphones",
    brand: "ApexMobile",
    rating: 4.4,
    reviewCount: 376,
    stock: 65,
    sellerId: "s1",
    createdAt: "2024-04-01",
  },
  {
    id: "17",
    name: "Creator Note",
    description:
      "Rugged yet beautiful phone featuring earth-themed stock wallpapers and robust drop protection.",
    price: 699.99,
    images: ["/images/photo12.webp"],
    category: "smartphones",
    brand: "Horizon",
    rating: 4.7,
    reviewCount: 280,
    stock: 20,
    sellerId: "s2",
    createdAt: "2024-04-03",
  },
  {
    id: "18",
    name: "Desk Station Tab",
    description:
      "A fordable smartphone that transforms into a compact tablet, perfect for on-the-go productivity and media consumption.",
    price: 899.99,
    images: ["/images/photo17.webp"],
    category: "smartphones tablets foldables",
    brand: "NovaTech",
    rating: 4.8,
    reviewCount: 190,
    stock: 18,
    sellerId: "s3",
    createdAt: "2024-04-05",
  },
  {
    id: "19",
    name: "Trio Slate Stack",
    description:
      "A multi-device bundle or choice of premium matte smartphones to match any corporate look.",
    price: 720.0,
    images: ["/images/photo18.webp"],
    category: "smartphones",
    brand: "Zenith",
    rating: 4.5,
    reviewCount: 460,
    stock: 40,
    sellerId: "s3",
    createdAt: "2024-04-08",
  },
  {
    id: "20",
    name: "Retro Metallic 2000",
    description:
      "Nostalgic feature phone with a physical keypad, robust construction, and legendary weeks-long battery life.",
    price: 49.99,
    images: ["/images/photo19.webp"],
    category: "budget-phones",
    brand: "ClassicTech",
    rating: 4.7,
    reviewCount: 1105,
    stock: 150,
    sellerId: "s1",
    createdAt: "2024-04-10",
  },
  {
    id: "21",
    name: "Pocket Classic Yellow",
    description:
      "Compact classic candybar feature phone placed on an energetic yellow background. True vintage style.",
    price: 39.99,
    images: ["/images/photo20.webp"],
    category: "budget-phones",
    brand: "ClassicTech",
    rating: 4.3,
    reviewCount: 642,
    stock: 200,
    sellerId: "s2",
    createdAt: "2024-04-12",
  },
  {
    id: "22",
    name: "Vintage Minimal Handset",
    description:
      "Elegant retro feature phone with basic calling, texting, and an ultra-durable casing.",
    price: 45.0,
    images: ["/images/photo21.webp"],
    category: "budget-phones",
    brand: "ClassicTech",
    rating: 4.5,
    reviewCount: 328,
    stock: 95,
    sellerId: "s3",
    createdAt: "2024-04-15",
  },
  {
    id: "23",
    name: "Rugged Secure Bar Phone",
    description:
      "Heavy-duty tactile buttons feature phone equipped with a powerful built-in flashlight and robust signal receiver.",
    price: 59.99,
    originalPrice: 69.99,
    images: ["/images/photo22.webp"],
    category: "budget-phones",
    brand: "ClassicTech",
    rating: 4.6,
    reviewCount: 812,
    stock: 130,
    sellerId: "s1",
    createdAt: "2024-04-18",
  },
];
