import type { Product, Category } from '../types';

export const mockCategories: Category[] = [
  { id: '1', name: 'Electronics', slug: 'electronics' },
  { id: '2', name: 'Fashion', slug: 'fashion' },
  { id: '3', name: 'Home & Living', slug: 'home-living' },
  { id: '4', name: 'Sports', slug: 'sports' },
  { id: '5', name: 'Books', slug: 'books' },
  { id: '6', name: 'Beauty', slug: 'beauty' },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Wireless Noise Cancelling Headphones',
    description: 'Premium over-ear headphones with active noise cancellation, 30-hour battery life, and Hi-Res audio support.',
    price: 249.99,
    originalPrice: 349.99,
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500'],
    category: 'Electronics',
    brand: 'AudioPro',
    rating: 4.5,
    reviewCount: 2341,
    stock: 50,
    sellerId: 's1',
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Smart Fitness Watch Pro',
    description: 'Advanced fitness tracker with GPS, heart rate monitoring, and 14-day battery life.',
    price: 199.99,
    originalPrice: 279.99,
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500'],
    category: 'Electronics',
    brand: 'FitTech',
    rating: 4.3,
    reviewCount: 1876,
    stock: 35,
    sellerId: 's2',
    createdAt: '2024-02-20',
  },
  {
    id: '3',
    name: 'Organic Cotton Premium T-Shirt',
    description: 'Sustainably sourced organic cotton t-shirt with a relaxed fit and premium feel.',
    price: 39.99,
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500'],
    category: 'Fashion',
    brand: 'EcoWear',
    rating: 4.7,
    reviewCount: 892,
    stock: 200,
    sellerId: 's3',
    createdAt: '2024-03-10',
  },
  {
    id: '4',
    name: 'Minimalist Desk Lamp',
    description: 'Elegant LED desk lamp with adjustable brightness, color temperature, and wireless charging base.',
    price: 79.99,
    originalPrice: 99.99,
    images: ['https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=500'],
    category: 'Home & Living',
    brand: 'LumiDesign',
    rating: 4.6,
    reviewCount: 567,
    stock: 80,
    sellerId: 's1',
    createdAt: '2024-01-25',
  },
  {
    id: '5',
    name: 'Professional Running Shoes',
    description: 'Lightweight performance running shoes with responsive cushioning and breathable mesh upper.',
    price: 129.99,
    originalPrice: 159.99,
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500'],
    category: 'Sports',
    brand: 'SwiftRun',
    rating: 4.4,
    reviewCount: 1432,
    stock: 120,
    sellerId: 's2',
    createdAt: '2024-02-15',
  },
  {
    id: '6',
    name: 'Portable Bluetooth Speaker',
    description: 'Waterproof portable speaker with 360° sound, 20-hour battery, and built-in microphone.',
    price: 89.99,
    images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500'],
    category: 'Electronics',
    brand: 'SoundWave',
    rating: 4.2,
    reviewCount: 2103,
    stock: 65,
    sellerId: 's3',
    createdAt: '2024-03-05',
  },
  {
    id: '7',
    name: 'Leather Crossbody Bag',
    description: 'Handcrafted genuine leather crossbody bag with adjustable strap and multiple compartments.',
    price: 149.99,
    originalPrice: 189.99,
    images: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500'],
    category: 'Fashion',
    brand: 'CraftLux',
    rating: 4.8,
    reviewCount: 421,
    stock: 30,
    sellerId: 's1',
    createdAt: '2024-01-30',
  },
  {
    id: '8',
    name: 'Scented Soy Candle Set',
    description: 'Set of 3 hand-poured soy candles with natural essential oils. Lavender, Vanilla, and Eucalyptus.',
    price: 34.99,
    images: ['https://images.unsplash.com/photo-1602028915047-37269d1a73f7?w=500'],
    category: 'Home & Living',
    brand: 'AromaBliss',
    rating: 4.9,
    reviewCount: 738,
    stock: 150,
    sellerId: 's2',
    createdAt: '2024-02-28',
  },
];
